### ISSUE TITLE
ScrollView cannot be cast to TextView Exception

### ISSUE THREAD

**Issue by patelakshay13890** [ened/Android-MarqueeView#5]
java.lang.ClassCastException: android.widget.ScrollView cannot be cast to android.widget.TextView
at asia.ivity.android.marqueeview.MarqueeView.initView(MarqueeView.java:310)
at asia.ivity.android.marqueeview.MarqueeView.onLayout(MarqueeView.java:182)

**Comment by matthijs2704** [comment]
You should use an TextView as child of the MarqueeView instead of a ScrollView

**Comment by gewoonrik** [comment]
I think #6 fixes this.
